
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sieepgujumwjauyoahzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpZWVwZ3VqdW13amF1eW9haHpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0Mzg1MzgsImV4cCI6MjA2MjAxNDUzOH0.4hJEuIa2KGJ0Vg7BdUtKo-Mp4_F30WQ7ixyhLRmfCA0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    storageKey: 'resonance-auth-key',
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});
